# Generated by Django 5.2.17 on 2026-09-28 09:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConversionJob',
            fields=[
                ('job_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', '대기중'), ('processing', '변환중'), ('done', '완료'), ('failed', '실패'), ('expired', '만료(파일삭제됨)')], default='pending', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('downloaded_at', models.DateTimeField(blank=True, null=True)),
                ('purged_at', models.DateTimeField(blank=True, null=True)),
                ('enable_ocr', models.BooleanField(default=False)),
                ('ocr_lang', models.CharField(default='kor', max_length=16)),
                ('input_object_key', models.CharField(max_length=255)),
                ('output_object_key', models.CharField(blank=True, max_length=255)),
                ('progress_stage', models.CharField(blank=True, max_length=16)),
                ('progress_current_page', models.IntegerField(default=0)),
                ('progress_total_pages', models.IntegerField(default=0)),
                ('progress_message', models.CharField(blank=True, max_length=255)),
                ('result_success', models.BooleanField(null=True)),
                ('result_warnings', models.JSONField(default=list)),
                ('result_errors', models.JSONField(default=list)),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'created_at'], name='converter_c_status_ba430f_idx')],
            },
        ),
    ]
